// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TEST100.Migrations
{
    [DbContext(typeof(BT))]
    [Migration("20230628074835_Create_table_NVVBN")]
    partial class Create_table_NVVBN
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("TEST100.Models.NVVBN", b =>
                {
                    b.Property<string>("Quequan")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Quequan");

                    b.ToTable("NVVBN");
                });
#pragma warning restore 612, 618
        }
    }
}
