// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TEST100.Migrations
{
    [DbContext(typeof(BT))]
    [Migration("20230628083034_Create_ForeignKey_table_NVVHN")]
    partial class Create_ForeignKey_table_NVVHN
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("TEST100.Models.NVVBN", b =>
                {
                    b.Property<string>("Quequan")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Quequan");

                    b.ToTable("NVVBN");
                });

            modelBuilder.Entity("TEST100.Models.NVVHN", b =>
                {
                    b.Property<string>("Quequan")
                        .HasColumnType("TEXT");

                    b.Property<string>("NGo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sonha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Quequan");

                    b.ToTable("NVVHN");
                });

            modelBuilder.Entity("TEST100.Models.NVVHN", b =>
                {
                    b.HasOne("TEST100.Models.NVVBN", "NVVBN")
                        .WithMany()
                        .HasForeignKey("Quequan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NVVBN");
                });
#pragma warning restore 612, 618
        }
    }
}
